# Generated by Django 3.2.8 on 2021-12-30 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='HTML_content',
        ),
    ]
